import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillGithub, AiFillLinkedin, AiFillTwitterCircle} from "react-icons/ai"
import Image from "next/image";
import deved from "../../public/dev-ed-wave.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>Timon Hosch Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>

        {/* Section One */}
        <section className='min-h-screen'>
          <nav className='mb-10 py-10 flex justify-between'>
            <h1 className='text-xl font-burtons'>T.H.</h1> 
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='somelink'>github</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Timon Hosch</h2>
            <h3 className='text-2xl py-2'>MERN Stack Web-Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>lorem ipsum dolor sit amet some text about how awesome I am and what I provide to you</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillGithub/>
            <AiFillLinkedin/>
            <AiFillTwitterCircle/>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 to-white rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} fill className='object-cover'/>
          </div>
        </section>

        {/* Section Two */}
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I Offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Since my beginning of my journey as a freelance designner and developer, I've done remote work for</p>
          </div>
        </section>
      </main>
    </>
  )
}
